import express from 'express';
import nodemailer from 'nodemailer';
import Diagnostic from '../models/Diagnostic.js';
import { updatePartAnalytics } from '../services/maintenancePredictor.js';

const router = express.Router();

const diagnosisDatabase = {
  'engine noise': [
    { name: 'Engine Block', position: { x: 0, y: 0, z: 2 } },
    { name: 'Timing Belt', position: { x: 0, y: 0.5, z: 2 } }
  ],
  'brake issues': [
    { name: 'Brake Pads', position: { x: -1.5, y: -1, z: 1 } },
    { name: 'Brake Rotors', position: { x: -1.5, y: -1, z: 1 } },
    { name: 'Brake Pads', position: { x: 1.5, y: -1, z: 1 } },
    { name: 'Brake Rotors', position: { x: 1.5, y: -1, z: 1 } }
  ],
  'transmission': [
    { name: 'Transmission', position: { x: 0, y: -0.5, z: 0 } },
    { name: 'Clutch', position: { x: 0, y: -0.5, z: 0.5 } }
  ],
  'steering': [
    { name: 'Steering Rack', position: { x: 0, y: -0.3, z: 1.5 } },
    { name: 'Power Steering Pump', position: { x: -0.5, y: 0, z: 1.8 } }
  ],
  'suspension': [
    { name: 'Front Suspension', position: { x: -1.5, y: -0.8, z: 1.5 } },
    { name: 'Front Suspension', position: { x: 1.5, y: -0.8, z: 1.5 } },
    { name: 'Shock Absorbers', position: { x: -1.5, y: -0.8, z: -1.5 } },
    { name: 'Shock Absorbers', position: { x: 1.5, y: -0.8, z: -1.5 } }
  ],
  'battery': [
    { name: 'Battery', position: { x: -1, y: 0, z: 1.5 } },
    { name: 'Alternator', position: { x: -0.7, y: 0, z: 2 } }
  ],
  'exhaust': [
    { name: 'Exhaust Manifold', position: { x: 0, y: -0.5, z: 1.5 } },
    { name: 'Catalytic Converter', position: { x: 0, y: -0.8, z: 0 } },
    { name: 'Muffler', position: { x: 0, y: -0.8, z: -2 } }
  ],
  'cooling': [
    { name: 'Radiator', position: { x: 0, y: 0, z: 2.5 } },
    { name: 'Water Pump', position: { x: 0.5, y: 0, z: 2 } },
    { name: 'Thermostat', position: { x: 0.3, y: 0.2, z: 2 } }
  ]
};

const findAffectedParts = (issue) => {
  const lowerIssue = issue.toLowerCase();

  for (const [key, parts] of Object.entries(diagnosisDatabase)) {
    if (lowerIssue.includes(key)) {
      return parts;
    }
  }

  return [{ name: 'General Inspection Required', position: { x: 0, y: 0, z: 0 } }];
};

router.post('/diagnose', async (req, res) => {
  try {
    const { carMake, carModel, year, issue, userEmail } = req.body;

    const affectedParts = findAffectedParts(issue);

    const diagnostic = new Diagnostic({
      carMake,
      carModel,
      year,
      issue,
      affectedParts,
      userEmail
    });

    await diagnostic.save();

    // Update part analytics with this diagnostic data
    await updatePartAnalytics(diagnostic);

    res.json({
      diagnostic,
      affectedParts
    });
  } catch (error) {
    res.status(500).json({ message: 'Server error', error: error.message });
  }
});

router.post('/send-report', async (req, res) => {
  try {
    const { email, carMake, carModel, year, issue, affectedParts } = req.body;

    if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
      return res.status(200).json({
        message: 'Email configuration not set up. Report generated but not sent.',
        success: false
      });
    }

    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT,
      secure: false,
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS
      }
    });

    const partsList = affectedParts
      .map(part => `- ${part.name}`)
      .join('\n');

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: email,
      subject: `RightPart Diagnostic Report - ${carMake} ${carModel} ${year}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <div style="background: linear-gradient(135deg, #B91C1C 0%, #DC2626 100%); padding: 20px; text-align: center;">
            <h1 style="color: #FFD700; margin: 0;">🦅 RightPart Diagnostic Report</h1>
          </div>

          <div style="padding: 20px; background: #f5f5f5;">
            <h2 style="color: #B91C1C;">Vehicle Information</h2>
            <p><strong>Make:</strong> ${carMake}</p>
            <p><strong>Model:</strong> ${carModel}</p>
            <p><strong>Year:</strong> ${year}</p>

            <h2 style="color: #B91C1C;">Reported Issue</h2>
            <p>${issue}</p>

            <h2 style="color: #B91C1C;">Affected Parts</h2>
            <pre style="background: white; padding: 15px; border-left: 4px solid #DC2626;">${partsList}</pre>

            <div style="margin-top: 30px; padding: 15px; background: white; border-radius: 5px;">
              <p style="color: #666; margin: 0;">
                This diagnostic report was generated by RightPart.
                For more information or to search for replacement parts, visit our marketplace.
              </p>
            </div>
          </div>

          <div style="background: #1F2937; padding: 15px; text-align: center; color: white;">
            <p style="margin: 0;">Powered by RightPart - The Global Car Parts Marketplace</p>
          </div>
        </div>
      `
    };

    await transporter.sendMail(mailOptions);

    res.json({
      message: 'Report sent successfully',
      success: true
    });
  } catch (error) {
    res.status(500).json({
      message: 'Failed to send email',
      error: error.message,
      success: false
    });
  }
});

export default router;
